FROM python:3.12-slim

WORKDIR /app

COPY . /app

RUN apt-get update && apt-get install -y bash

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080

ENV NAME FastAPI

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
