services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./Dockerfile.backend
    healthCheckPath: /health

  - type: web
    name: nginx
    env: docker
    dockerfilePath: ./nginx/Dockerfile
    startCommand: /bin/bash /etc/nginx/entrypoint.sh
    envVars:
      - key: BACKEND_HOST
        fromService:
          type: web
          name: backend
          property: host
      - key: BACKEND_PORT
        fromService:
          type: web
          name: backend
          property: port
